import { ParamValueSerializedTypeMap } from "@polygonjs/polygonjs/dist/src/engine/params/types/ParamValueSerializedTypeMap";

import { PolyScene } from "@polygonjs/polygonjs/dist/src/engine/scene/PolyScene";
// obj
import { CopNetworkObjNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/obj/CopNetwork";
import { GeoObjNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/obj/Geo";
// cop
import { EnvMapCopNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/cop/EnvMap";
import { ImageEXRCopNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/cop/ImageEXR";
import { SDFExporterCopNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/cop/SDFExporter";
import { SDFFromObjectCopNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/cop/SDFFromObject";
import { SDFFromUrlCopNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/cop/SDFFromUrl";
// sop
import { ActorSopNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/sop/Actor";
import { BoxLinesSopNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/sop/BoxLines";
import { BoxSopNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/sop/Box";
import { CopNetworkSopNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/sop/CopNetwork";
import { EmptyObjectSopNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/sop/EmptyObject";
import { FileGLTFSopNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/sop/FileGLTF";
import { HemisphereLightSopNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/sop/HemisphereLight";
import { MaterialSopNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/sop/Material";
import { MaterialsNetworkSopNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/sop/MaterialsNetwork";
import { MergeSopNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/sop/Merge";
import { PerspectiveCameraSopNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/sop/PerspectiveCamera";
import { SetChildrenSopNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/sop/SetChildren";
import { TransformSopNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/sop/Transform";
// actor
import { CursorActorNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/actor/Cursor";
import { FloatToVec3ActorNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/actor/FloatToVec3";
import { MaxActorNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/actor/Max";
import { MultAddActorNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/actor/MultAdd";
import { OnTickActorNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/actor/OnTick";
import { SetMaterialUniformActorNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/actor/SetMaterialUniform";
import { SetObjectPolarTransformActorNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/actor/SetObjectPolarTransform";
import { SetObjectRotationActorNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/actor/SetObjectRotation";
import { Vec2ToFloatActorNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/actor/Vec2ToFloat";
// mat
import { AnimationsNetworkMatNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/mat/AnimationsNetwork";
import { EventsNetworkMatNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/mat/EventsNetwork";
import { MeshStandardMatNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/mat/MeshStandard";
import { RayMarchingBuilderMatNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/mat/RayMarchingBuilder";
// anim
import { DurationAnimNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/anim/Duration";
import { EasingAnimNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/anim/Easing";
import { NullAnimNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/anim/Null";
import { PlayAnimNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/anim/Play";
import { PropertyNameAnimNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/anim/PropertyName";
import { PropertyValueAnimNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/anim/PropertyValue";
import { TargetAnimNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/anim/Target";
// event
import { AnimationEventNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/event/Animation";
import { SceneEventNode } from "@polygonjs/polygonjs/dist/src/engine/nodes/event/Scene";

export class PolySceneWithNodeMap_rhino extends PolyScene {
  node(path: "/COP"): CopNetworkObjNode;
  node(path: "/COP/envMap"): EnvMapCopNode;
  node(path: "/COP/imageEnv"): ImageEXRCopNode;
  node(path: "/cameras"): GeoObjNode;
  node(path: "/cameras/perspectiveCamera_MAIN"): PerspectiveCameraSopNode;
  node(path: "/cameras/emptyObject1"): EmptyObjectSopNode;
  node(path: "/cameras/setChildren1"): SetChildrenSopNode;
  node(path: "/cameras/transform1"): TransformSopNode;
  node(path: "/cameras/actor1"): ActorSopNode;
  node(path: "/cameras/actor1/onTick1"): OnTickActorNode;
  node(
    path: "/cameras/actor1/setObjectPolarTransform1"
  ): SetObjectPolarTransformActorNode;
  node(path: "/cameras/actor1/cursor1"): CursorActorNode;
  node(path: "/cameras/actor1/vec2ToFloat1"): Vec2ToFloatActorNode;
  node(path: "/cameras/actor1/multAdd1"): MultAddActorNode;
  node(path: "/cameras/actor1/multAdd2"): MultAddActorNode;
  node(path: "/cameras/actor2"): ActorSopNode;
  node(path: "/cameras/actor2/cursor1"): CursorActorNode;
  node(path: "/cameras/actor2/vec2ToFloat1"): Vec2ToFloatActorNode;
  node(path: "/cameras/actor2/multAdd1"): MultAddActorNode;
  node(path: "/cameras/actor2/multAdd2"): MultAddActorNode;
  node(path: "/cameras/actor2/setObjectRotation1"): SetObjectRotationActorNode;
  node(path: "/cameras/actor2/floatToVec3_1"): FloatToVec3ActorNode;
  node(path: "/cameras/actor2/onTick1"): OnTickActorNode;
  node(path: "/cameras/actor2/max1"): MaxActorNode;
  node(path: "/lights"): GeoObjNode;
  node(path: "/lights/hemisphereLight1"): HemisphereLightSopNode;
  node(path: "/raymarchedObject"): GeoObjNode;
  node(path: "/raymarchedObject/box1"): BoxSopNode;
  node(path: "/raymarchedObject/boxLines1"): BoxLinesSopNode;
  node(path: "/raymarchedObject/fileGLTF1"): FileGLTFSopNode;
  node(path: "/raymarchedObject/material1"): MaterialSopNode;
  node(path: "/raymarchedObject/material2"): MaterialSopNode;
  node(path: "/raymarchedObject/merge1"): MergeSopNode;
  node(path: "/raymarchedObject/COP"): CopNetworkSopNode;
  node(path: "/raymarchedObject/COP/SDFExporter1"): SDFExporterCopNode;
  node(path: "/raymarchedObject/COP/SDFFromObject1"): SDFFromObjectCopNode;
  node(path: "/raymarchedObject/COP/SDFFromUrl1"): SDFFromUrlCopNode;
  node(path: "/raymarchedObject/MAT"): MaterialsNetworkSopNode;
  node(path: "/raymarchedObject/MAT/meshStandard1"): MeshStandardMatNode;
  node(
    path: "/raymarchedObject/MAT/rayMarchingBuilder1"
  ): RayMarchingBuilderMatNode;
  node(
    path: "/raymarchedObject/MAT/animationsNetwork1"
  ): AnimationsNetworkMatNode;
  node(
    path: "/raymarchedObject/MAT/animationsNetwork1/duration1"
  ): DurationAnimNode;
  node(
    path: "/raymarchedObject/MAT/animationsNetwork1/easing1"
  ): EasingAnimNode;
  node(
    path: "/raymarchedObject/MAT/animationsNetwork1/target1"
  ): TargetAnimNode;
  node(
    path: "/raymarchedObject/MAT/animationsNetwork1/propertyName1"
  ): PropertyNameAnimNode;
  node(
    path: "/raymarchedObject/MAT/animationsNetwork1/propertyValue1"
  ): PropertyValueAnimNode;
  node(
    path: "/raymarchedObject/MAT/animationsNetwork1/propertyValue2"
  ): PropertyValueAnimNode;
  node(path: "/raymarchedObject/MAT/animationsNetwork1/PLAY"): NullAnimNode;
  node(path: "/raymarchedObject/MAT/animationsNetwork1/RESET"): NullAnimNode;
  node(path: "/raymarchedObject/MAT/animationsNetwork1/CONTROLS"): PlayAnimNode;
  node(path: "/raymarchedObject/MAT/eventsNetwork1"): EventsNetworkMatNode;
  node(path: "/raymarchedObject/MAT/eventsNetwork1/scene1"): SceneEventNode;
  node(
    path: "/raymarchedObject/MAT/eventsNetwork1/animation1"
  ): AnimationEventNode;
  node(path: "/raymarchedObject/actor1"): ActorSopNode;
  node(path: "/raymarchedObject/actor1/onTick1"): OnTickActorNode;
  node(
    path: "/raymarchedObject/actor1/setMaterialUniform1"
  ): SetMaterialUniformActorNode;
  node(
    path: string
  ): any /* we need any for now as otherwise an error occurs when adding plugins to the overloaded methods */ {
    return super.node(path);
  }
}

export interface PolySceneProps_rhino {
  "COP-envMap--useCameraRenderer"?: ParamValueSerializedTypeMap["boolean"];
  "COP-imageEnv--url"?: ParamValueSerializedTypeMap["string"];
  "COP-imageEnv--reload"?: ParamValueSerializedTypeMap["button"];
  "COP-imageEnv--tencoding"?: ParamValueSerializedTypeMap["boolean"];
  "COP-imageEnv--encoding"?: ParamValueSerializedTypeMap["integer"];
  "COP-imageEnv--tmapping"?: ParamValueSerializedTypeMap["boolean"];
  "COP-imageEnv--mapping"?: ParamValueSerializedTypeMap["integer"];
  "COP-imageEnv--twrap"?: ParamValueSerializedTypeMap["boolean"];
  "COP-imageEnv--wrapS"?: ParamValueSerializedTypeMap["integer"];
  "COP-imageEnv--wrapT"?: ParamValueSerializedTypeMap["integer"];
  "COP-imageEnv--tminFilter"?: ParamValueSerializedTypeMap["boolean"];
  "COP-imageEnv--minFilter"?: ParamValueSerializedTypeMap["integer"];
  "COP-imageEnv--tmagFilter"?: ParamValueSerializedTypeMap["boolean"];
  "COP-imageEnv--magFilter"?: ParamValueSerializedTypeMap["integer"];
  "COP-imageEnv--tanisotropy"?: ParamValueSerializedTypeMap["boolean"];
  "COP-imageEnv--useRendererMaxAnisotropy"?: ParamValueSerializedTypeMap["boolean"];
  "COP-imageEnv--anisotropy"?: ParamValueSerializedTypeMap["integer"];
  "COP-imageEnv--tflipY"?: ParamValueSerializedTypeMap["boolean"];
  "COP-imageEnv--flipY"?: ParamValueSerializedTypeMap["boolean"];
  "COP-imageEnv--ttransform"?: ParamValueSerializedTypeMap["boolean"];
  "COP-imageEnv--offset"?: ParamValueSerializedTypeMap["vector2"];
  "COP-imageEnv--offset-offsetx"?: ParamValueSerializedTypeMap["float"];
  "COP-imageEnv--offset-offsety"?: ParamValueSerializedTypeMap["float"];
  "COP-imageEnv--offsetx"?: ParamValueSerializedTypeMap["float"];
  "COP-imageEnv--offsety"?: ParamValueSerializedTypeMap["float"];
  "COP-imageEnv--repeat"?: ParamValueSerializedTypeMap["vector2"];
  "COP-imageEnv--repeat-repeatx"?: ParamValueSerializedTypeMap["float"];
  "COP-imageEnv--repeat-repeaty"?: ParamValueSerializedTypeMap["float"];
  "COP-imageEnv--repeatx"?: ParamValueSerializedTypeMap["float"];
  "COP-imageEnv--repeaty"?: ParamValueSerializedTypeMap["float"];
  "COP-imageEnv--rotation"?: ParamValueSerializedTypeMap["float"];
  "COP-imageEnv--center"?: ParamValueSerializedTypeMap["vector2"];
  "COP-imageEnv--center-centerx"?: ParamValueSerializedTypeMap["float"];
  "COP-imageEnv--center-centery"?: ParamValueSerializedTypeMap["float"];
  "COP-imageEnv--centerx"?: ParamValueSerializedTypeMap["float"];
  "COP-imageEnv--centery"?: ParamValueSerializedTypeMap["float"];
  "COP-imageEnv--tadvanced"?: ParamValueSerializedTypeMap["boolean"];
  "COP-imageEnv--tformat"?: ParamValueSerializedTypeMap["boolean"];
  "COP-imageEnv--format"?: ParamValueSerializedTypeMap["integer"];
  "COP-imageEnv--ttype"?: ParamValueSerializedTypeMap["boolean"];
  "COP-imageEnv--type"?: ParamValueSerializedTypeMap["integer"];
  "COP-imageEnv--checkFileType"?: ParamValueSerializedTypeMap["boolean"];
  "cameras--transform"?: ParamValueSerializedTypeMap["folder"];
  "cameras--keepPosWhenParenting"?: ParamValueSerializedTypeMap["boolean"];
  "cameras--rotationOrder"?: ParamValueSerializedTypeMap["integer"];
  "cameras--t"?: ParamValueSerializedTypeMap["vector3"];
  "cameras--t-tx"?: ParamValueSerializedTypeMap["float"];
  "cameras--t-ty"?: ParamValueSerializedTypeMap["float"];
  "cameras--t-tz"?: ParamValueSerializedTypeMap["float"];
  "cameras--tx"?: ParamValueSerializedTypeMap["float"];
  "cameras--ty"?: ParamValueSerializedTypeMap["float"];
  "cameras--tz"?: ParamValueSerializedTypeMap["float"];
  "cameras--r"?: ParamValueSerializedTypeMap["vector3"];
  "cameras--r-rx"?: ParamValueSerializedTypeMap["float"];
  "cameras--r-ry"?: ParamValueSerializedTypeMap["float"];
  "cameras--r-rz"?: ParamValueSerializedTypeMap["float"];
  "cameras--rx"?: ParamValueSerializedTypeMap["float"];
  "cameras--ry"?: ParamValueSerializedTypeMap["float"];
  "cameras--rz"?: ParamValueSerializedTypeMap["float"];
  "cameras--s"?: ParamValueSerializedTypeMap["vector3"];
  "cameras--s-sx"?: ParamValueSerializedTypeMap["float"];
  "cameras--s-sy"?: ParamValueSerializedTypeMap["float"];
  "cameras--s-sz"?: ParamValueSerializedTypeMap["float"];
  "cameras--sx"?: ParamValueSerializedTypeMap["float"];
  "cameras--sy"?: ParamValueSerializedTypeMap["float"];
  "cameras--sz"?: ParamValueSerializedTypeMap["float"];
  "cameras--scale"?: ParamValueSerializedTypeMap["float"];
  "cameras--matrixAutoUpdate"?: ParamValueSerializedTypeMap["boolean"];
  "cameras--updateTransformFromObject"?: ParamValueSerializedTypeMap["button"];
  "cameras--display"?: ParamValueSerializedTypeMap["boolean"];
  "cameras--renderOrder"?: ParamValueSerializedTypeMap["integer"];
  "cameras-perspectiveCamera_MAIN--fov"?: ParamValueSerializedTypeMap["float"];
  "cameras-perspectiveCamera_MAIN--near"?: ParamValueSerializedTypeMap["float"];
  "cameras-perspectiveCamera_MAIN--far"?: ParamValueSerializedTypeMap["float"];
  "cameras-perspectiveCamera_MAIN--position"?: ParamValueSerializedTypeMap["vector3"];
  "cameras-perspectiveCamera_MAIN--position-positionx"?: ParamValueSerializedTypeMap["float"];
  "cameras-perspectiveCamera_MAIN--position-positiony"?: ParamValueSerializedTypeMap["float"];
  "cameras-perspectiveCamera_MAIN--position-positionz"?: ParamValueSerializedTypeMap["float"];
  "cameras-perspectiveCamera_MAIN--positionx"?: ParamValueSerializedTypeMap["float"];
  "cameras-perspectiveCamera_MAIN--positiony"?: ParamValueSerializedTypeMap["float"];
  "cameras-perspectiveCamera_MAIN--positionz"?: ParamValueSerializedTypeMap["float"];
  "cameras-perspectiveCamera_MAIN--rotation"?: ParamValueSerializedTypeMap["vector3"];
  "cameras-perspectiveCamera_MAIN--rotation-rotationx"?: ParamValueSerializedTypeMap["float"];
  "cameras-perspectiveCamera_MAIN--rotation-rotationy"?: ParamValueSerializedTypeMap["float"];
  "cameras-perspectiveCamera_MAIN--rotation-rotationz"?: ParamValueSerializedTypeMap["float"];
  "cameras-perspectiveCamera_MAIN--rotationx"?: ParamValueSerializedTypeMap["float"];
  "cameras-perspectiveCamera_MAIN--rotationy"?: ParamValueSerializedTypeMap["float"];
  "cameras-perspectiveCamera_MAIN--rotationz"?: ParamValueSerializedTypeMap["float"];
  "cameras-perspectiveCamera_MAIN--showHelper"?: ParamValueSerializedTypeMap["boolean"];
  "cameras-perspectiveCamera_MAIN--matrixAutoUpdate"?: ParamValueSerializedTypeMap["boolean"];
  "cameras-perspectiveCamera_MAIN--name"?: ParamValueSerializedTypeMap["string"];
  "cameras-perspectiveCamera_MAIN--updateTransformFromCamera"?: ParamValueSerializedTypeMap["button"];
  "cameras-emptyObject1--type"?: ParamValueSerializedTypeMap["string"];
  "cameras-setChildren1--clearExistingChildren"?: ParamValueSerializedTypeMap["boolean"];
  "cameras-transform1--applyOn"?: ParamValueSerializedTypeMap["integer"];
  "cameras-transform1--objectMode"?: ParamValueSerializedTypeMap["integer"];
  "cameras-transform1--objectTransformSpace"?: ParamValueSerializedTypeMap["integer"];
  "cameras-transform1--group"?: ParamValueSerializedTypeMap["string"];
  "cameras-transform1--rotationOrder"?: ParamValueSerializedTypeMap["integer"];
  "cameras-transform1--t"?: ParamValueSerializedTypeMap["vector3"];
  "cameras-transform1--t-tx"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--t-ty"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--t-tz"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--tx"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--ty"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--tz"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--r"?: ParamValueSerializedTypeMap["vector3"];
  "cameras-transform1--r-rx"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--r-ry"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--r-rz"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--rx"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--ry"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--rz"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--s"?: ParamValueSerializedTypeMap["vector3"];
  "cameras-transform1--s-sx"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--s-sy"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--s-sz"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--sx"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--sy"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--sz"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--scale"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--pivot"?: ParamValueSerializedTypeMap["vector3"];
  "cameras-transform1--pivot-pivotx"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--pivot-pivoty"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--pivot-pivotz"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--pivotx"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--pivoty"?: ParamValueSerializedTypeMap["float"];
  "cameras-transform1--pivotz"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1--objectsMask"?: ParamValueSerializedTypeMap["string"];
  "cameras-actor1--useThisNode"?: ParamValueSerializedTypeMap["boolean"];
  "cameras-actor1--node"?: ParamValueSerializedTypeMap["node_path"];
  "cameras-actor1-setObjectPolarTransform1--center"?: ParamValueSerializedTypeMap["vector3"];
  "cameras-actor1-setObjectPolarTransform1--center-centerx"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-setObjectPolarTransform1--center-centery"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-setObjectPolarTransform1--center-centerz"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-setObjectPolarTransform1--centerx"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-setObjectPolarTransform1--centery"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-setObjectPolarTransform1--centerz"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-setObjectPolarTransform1--longitude"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-setObjectPolarTransform1--latitude"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-setObjectPolarTransform1--depth"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-cursor1--element"?: ParamValueSerializedTypeMap["integer"];
  "cameras-actor1-cursor1--cursor"?: ParamValueSerializedTypeMap["vector2"];
  "cameras-actor1-cursor1--cursor-cursorx"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-cursor1--cursor-cursory"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-cursor1--cursorx"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-cursor1--cursory"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-vec2ToFloat1--vec2"?: ParamValueSerializedTypeMap["vector2"];
  "cameras-actor1-vec2ToFloat1--vec2-vec2x"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-vec2ToFloat1--vec2-vec2y"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-vec2ToFloat1--vec2x"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-vec2ToFloat1--vec2y"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-multAdd1--value"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-multAdd1--preAdd"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-multAdd1--mult"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-multAdd1--postAdd"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-multAdd2--value"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-multAdd2--preAdd"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-multAdd2--mult"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor1-multAdd2--postAdd"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2--objectsMask"?: ParamValueSerializedTypeMap["string"];
  "cameras-actor2--useThisNode"?: ParamValueSerializedTypeMap["boolean"];
  "cameras-actor2--node"?: ParamValueSerializedTypeMap["node_path"];
  "cameras-actor2-cursor1--element"?: ParamValueSerializedTypeMap["integer"];
  "cameras-actor2-cursor1--cursor"?: ParamValueSerializedTypeMap["vector2"];
  "cameras-actor2-cursor1--cursor-cursorx"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-cursor1--cursor-cursory"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-cursor1--cursorx"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-cursor1--cursory"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-vec2ToFloat1--vec2"?: ParamValueSerializedTypeMap["vector2"];
  "cameras-actor2-vec2ToFloat1--vec2-vec2x"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-vec2ToFloat1--vec2-vec2y"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-vec2ToFloat1--vec2x"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-vec2ToFloat1--vec2y"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-multAdd1--value"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-multAdd1--preAdd"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-multAdd1--mult"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-multAdd1--postAdd"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-multAdd2--value"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-multAdd2--preAdd"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-multAdd2--mult"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-multAdd2--postAdd"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-setObjectRotation1--rotationOrder"?: ParamValueSerializedTypeMap["integer"];
  "cameras-actor2-setObjectRotation1--rotation"?: ParamValueSerializedTypeMap["vector3"];
  "cameras-actor2-setObjectRotation1--rotation-rotationx"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-setObjectRotation1--rotation-rotationy"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-setObjectRotation1--rotation-rotationz"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-setObjectRotation1--rotationx"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-setObjectRotation1--rotationy"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-setObjectRotation1--rotationz"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-setObjectRotation1--lerp"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-setObjectRotation1--updateMatrix"?: ParamValueSerializedTypeMap["boolean"];
  "cameras-actor2-floatToVec3_1--x"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-floatToVec3_1--y"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-floatToVec3_1--z"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-max1--max0"?: ParamValueSerializedTypeMap["float"];
  "cameras-actor2-max1--max1"?: ParamValueSerializedTypeMap["float"];
  "lights--transform"?: ParamValueSerializedTypeMap["folder"];
  "lights--keepPosWhenParenting"?: ParamValueSerializedTypeMap["boolean"];
  "lights--rotationOrder"?: ParamValueSerializedTypeMap["integer"];
  "lights--t"?: ParamValueSerializedTypeMap["vector3"];
  "lights--t-tx"?: ParamValueSerializedTypeMap["float"];
  "lights--t-ty"?: ParamValueSerializedTypeMap["float"];
  "lights--t-tz"?: ParamValueSerializedTypeMap["float"];
  "lights--tx"?: ParamValueSerializedTypeMap["float"];
  "lights--ty"?: ParamValueSerializedTypeMap["float"];
  "lights--tz"?: ParamValueSerializedTypeMap["float"];
  "lights--r"?: ParamValueSerializedTypeMap["vector3"];
  "lights--r-rx"?: ParamValueSerializedTypeMap["float"];
  "lights--r-ry"?: ParamValueSerializedTypeMap["float"];
  "lights--r-rz"?: ParamValueSerializedTypeMap["float"];
  "lights--rx"?: ParamValueSerializedTypeMap["float"];
  "lights--ry"?: ParamValueSerializedTypeMap["float"];
  "lights--rz"?: ParamValueSerializedTypeMap["float"];
  "lights--s"?: ParamValueSerializedTypeMap["vector3"];
  "lights--s-sx"?: ParamValueSerializedTypeMap["float"];
  "lights--s-sy"?: ParamValueSerializedTypeMap["float"];
  "lights--s-sz"?: ParamValueSerializedTypeMap["float"];
  "lights--sx"?: ParamValueSerializedTypeMap["float"];
  "lights--sy"?: ParamValueSerializedTypeMap["float"];
  "lights--sz"?: ParamValueSerializedTypeMap["float"];
  "lights--scale"?: ParamValueSerializedTypeMap["float"];
  "lights--matrixAutoUpdate"?: ParamValueSerializedTypeMap["boolean"];
  "lights--updateTransformFromObject"?: ParamValueSerializedTypeMap["button"];
  "lights--display"?: ParamValueSerializedTypeMap["boolean"];
  "lights--renderOrder"?: ParamValueSerializedTypeMap["integer"];
  "lights-hemisphereLight1--skyColor"?: ParamValueSerializedTypeMap["color"];
  "lights-hemisphereLight1--skyColor-skyColorr"?: ParamValueSerializedTypeMap["float"];
  "lights-hemisphereLight1--skyColor-skyColorg"?: ParamValueSerializedTypeMap["float"];
  "lights-hemisphereLight1--skyColor-skyColorb"?: ParamValueSerializedTypeMap["float"];
  "lights-hemisphereLight1--skyColorr"?: ParamValueSerializedTypeMap["float"];
  "lights-hemisphereLight1--skyColorg"?: ParamValueSerializedTypeMap["float"];
  "lights-hemisphereLight1--skyColorb"?: ParamValueSerializedTypeMap["float"];
  "lights-hemisphereLight1--groundColor"?: ParamValueSerializedTypeMap["color"];
  "lights-hemisphereLight1--groundColor-groundColorr"?: ParamValueSerializedTypeMap["float"];
  "lights-hemisphereLight1--groundColor-groundColorg"?: ParamValueSerializedTypeMap["float"];
  "lights-hemisphereLight1--groundColor-groundColorb"?: ParamValueSerializedTypeMap["float"];
  "lights-hemisphereLight1--groundColorr"?: ParamValueSerializedTypeMap["float"];
  "lights-hemisphereLight1--groundColorg"?: ParamValueSerializedTypeMap["float"];
  "lights-hemisphereLight1--groundColorb"?: ParamValueSerializedTypeMap["float"];
  "lights-hemisphereLight1--intensity"?: ParamValueSerializedTypeMap["float"];
  "lights-hemisphereLight1--position"?: ParamValueSerializedTypeMap["vector3"];
  "lights-hemisphereLight1--position-positionx"?: ParamValueSerializedTypeMap["float"];
  "lights-hemisphereLight1--position-positiony"?: ParamValueSerializedTypeMap["float"];
  "lights-hemisphereLight1--position-positionz"?: ParamValueSerializedTypeMap["float"];
  "lights-hemisphereLight1--positionx"?: ParamValueSerializedTypeMap["float"];
  "lights-hemisphereLight1--positiony"?: ParamValueSerializedTypeMap["float"];
  "lights-hemisphereLight1--positionz"?: ParamValueSerializedTypeMap["float"];
  "lights-hemisphereLight1--name"?: ParamValueSerializedTypeMap["string"];
  "raymarchedObject--transform"?: ParamValueSerializedTypeMap["folder"];
  "raymarchedObject--keepPosWhenParenting"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject--rotationOrder"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject--t"?: ParamValueSerializedTypeMap["vector3"];
  "raymarchedObject--t-tx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject--t-ty"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject--t-tz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject--tx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject--ty"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject--tz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject--r"?: ParamValueSerializedTypeMap["vector3"];
  "raymarchedObject--r-rx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject--r-ry"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject--r-rz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject--rx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject--ry"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject--rz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject--s"?: ParamValueSerializedTypeMap["vector3"];
  "raymarchedObject--s-sx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject--s-sy"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject--s-sz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject--sx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject--sy"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject--sz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject--scale"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject--matrixAutoUpdate"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject--updateTransformFromObject"?: ParamValueSerializedTypeMap["button"];
  "raymarchedObject--display"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject--renderOrder"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-box1--size"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-box1--sizes"?: ParamValueSerializedTypeMap["vector3"];
  "raymarchedObject-box1--sizes-sizesx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-box1--sizes-sizesy"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-box1--sizes-sizesz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-box1--sizesx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-box1--sizesy"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-box1--sizesz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-box1--divisions"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-box1--center"?: ParamValueSerializedTypeMap["vector3"];
  "raymarchedObject-box1--center-centerx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-box1--center-centery"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-box1--center-centerz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-box1--centerx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-box1--centery"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-box1--centerz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-boxLines1--size"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-boxLines1--sizes"?: ParamValueSerializedTypeMap["vector3"];
  "raymarchedObject-boxLines1--sizes-sizesx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-boxLines1--sizes-sizesy"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-boxLines1--sizes-sizesz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-boxLines1--sizesx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-boxLines1--sizesy"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-boxLines1--sizesz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-boxLines1--divisions"?: ParamValueSerializedTypeMap["vector3"];
  "raymarchedObject-boxLines1--divisions-divisionsx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-boxLines1--divisions-divisionsy"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-boxLines1--divisions-divisionsz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-boxLines1--divisionsx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-boxLines1--divisionsy"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-boxLines1--divisionsz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-boxLines1--center"?: ParamValueSerializedTypeMap["vector3"];
  "raymarchedObject-boxLines1--center-centerx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-boxLines1--center-centery"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-boxLines1--center-centerz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-boxLines1--centerx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-boxLines1--centery"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-boxLines1--centerz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-fileGLTF1--url"?: ParamValueSerializedTypeMap["string"];
  "raymarchedObject-fileGLTF1--draco"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-fileGLTF1--ktx2"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-fileGLTF1--matrixAutoUpdate"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-fileGLTF1--reload"?: ParamValueSerializedTypeMap["button"];
  "raymarchedObject-material1--group"?: ParamValueSerializedTypeMap["string"];
  "raymarchedObject-material1--applyToChildren"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-material1--assignMat"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-material1--material"?: ParamValueSerializedTypeMap["node_path"];
  "raymarchedObject-material1--cloneMat"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-material1--shareCustomUniforms"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-material1--swapCurrentTex"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-material1--texSrc0"?: ParamValueSerializedTypeMap["string"];
  "raymarchedObject-material1--texDest0"?: ParamValueSerializedTypeMap["string"];
  "raymarchedObject-material2--group"?: ParamValueSerializedTypeMap["string"];
  "raymarchedObject-material2--applyToChildren"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-material2--assignMat"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-material2--material"?: ParamValueSerializedTypeMap["node_path"];
  "raymarchedObject-material2--cloneMat"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-material2--shareCustomUniforms"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-material2--swapCurrentTex"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-material2--texSrc0"?: ParamValueSerializedTypeMap["string"];
  "raymarchedObject-material2--texDest0"?: ParamValueSerializedTypeMap["string"];
  "raymarchedObject-merge1--compact"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-merge1--inputsCount"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-COP-SDFExporter1--fileName"?: ParamValueSerializedTypeMap["string"];
  "raymarchedObject-COP-SDFExporter1--download"?: ParamValueSerializedTypeMap["button"];
  "raymarchedObject-COP-SDFFromObject1--geometry"?: ParamValueSerializedTypeMap["node_path"];
  "raymarchedObject-COP-SDFFromObject1--voxelSize"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromObject1--padding"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-COP-SDFFromObject1--resolution"?: ParamValueSerializedTypeMap["vector3"];
  "raymarchedObject-COP-SDFFromObject1--resolution-resolutionx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromObject1--resolution-resolutiony"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromObject1--resolution-resolutionz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromObject1--resolutionx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromObject1--resolutiony"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromObject1--resolutionz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromObject1--boundMin"?: ParamValueSerializedTypeMap["vector3"];
  "raymarchedObject-COP-SDFFromObject1--boundMin-boundMinx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromObject1--boundMin-boundMiny"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromObject1--boundMin-boundMinz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromObject1--boundMinx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromObject1--boundMiny"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromObject1--boundMinz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromObject1--boundMax"?: ParamValueSerializedTypeMap["vector3"];
  "raymarchedObject-COP-SDFFromObject1--boundMax-boundMaxx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromObject1--boundMax-boundMaxy"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromObject1--boundMax-boundMaxz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromObject1--boundMaxx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromObject1--boundMaxy"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromObject1--boundMaxz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromUrl1--url"?: ParamValueSerializedTypeMap["string"];
  "raymarchedObject-COP-SDFFromUrl1--reload"?: ParamValueSerializedTypeMap["button"];
  "raymarchedObject-COP-SDFFromUrl1--resolution"?: ParamValueSerializedTypeMap["vector3"];
  "raymarchedObject-COP-SDFFromUrl1--resolution-resolutionx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromUrl1--resolution-resolutiony"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromUrl1--resolution-resolutionz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromUrl1--resolutionx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromUrl1--resolutiony"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromUrl1--resolutionz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromUrl1--boundMin"?: ParamValueSerializedTypeMap["vector3"];
  "raymarchedObject-COP-SDFFromUrl1--boundMin-boundMinx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromUrl1--boundMin-boundMiny"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromUrl1--boundMin-boundMinz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromUrl1--boundMinx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromUrl1--boundMiny"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromUrl1--boundMinz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromUrl1--boundMax"?: ParamValueSerializedTypeMap["vector3"];
  "raymarchedObject-COP-SDFFromUrl1--boundMax-boundMaxx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromUrl1--boundMax-boundMaxy"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromUrl1--boundMax-boundMaxz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromUrl1--boundMaxx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromUrl1--boundMaxy"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-COP-SDFFromUrl1--boundMaxz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--default"?: ParamValueSerializedTypeMap["folder"];
  "raymarchedObject-MAT-meshStandard1--color"?: ParamValueSerializedTypeMap["color"];
  "raymarchedObject-MAT-meshStandard1--color-colorr"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--color-colorg"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--color-colorb"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--colorr"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--colorg"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--colorb"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--useVertexColors"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--transparent"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--opacity"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--alphaTest"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--textures"?: ParamValueSerializedTypeMap["folder"];
  "raymarchedObject-MAT-meshStandard1--useMap"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--map"?: ParamValueSerializedTypeMap["node_path"];
  "raymarchedObject-MAT-meshStandard1--useAlphaMap"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--alphaMap"?: ParamValueSerializedTypeMap["node_path"];
  "raymarchedObject-MAT-meshStandard1--useAOMap"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--aoMap"?: ParamValueSerializedTypeMap["node_path"];
  "raymarchedObject-MAT-meshStandard1--aoMapIntensity"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--useBumpMap"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--bumpMap"?: ParamValueSerializedTypeMap["node_path"];
  "raymarchedObject-MAT-meshStandard1--bumpScale"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--bumpBias"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--useDisplacementMap"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--displacementMap"?: ParamValueSerializedTypeMap["node_path"];
  "raymarchedObject-MAT-meshStandard1--displacementScale"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--displacementBias"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--emissive"?: ParamValueSerializedTypeMap["color"];
  "raymarchedObject-MAT-meshStandard1--emissive-emissiver"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--emissive-emissiveg"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--emissive-emissiveb"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--emissiver"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--emissiveg"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--emissiveb"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--useEmissiveMap"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--emissiveMap"?: ParamValueSerializedTypeMap["node_path"];
  "raymarchedObject-MAT-meshStandard1--emissiveIntensity"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--useEnvMap"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--envMap"?: ParamValueSerializedTypeMap["node_path"];
  "raymarchedObject-MAT-meshStandard1--envMapIntensity"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--useLightMap"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--lightMap"?: ParamValueSerializedTypeMap["node_path"];
  "raymarchedObject-MAT-meshStandard1--lightMapIntensity"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--useNormalMap"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--normalMap"?: ParamValueSerializedTypeMap["node_path"];
  "raymarchedObject-MAT-meshStandard1--normalMapType"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-MAT-meshStandard1--normalScale"?: ParamValueSerializedTypeMap["vector2"];
  "raymarchedObject-MAT-meshStandard1--normalScale-normalScalex"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--normalScale-normalScaley"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--normalScalex"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--normalScaley"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--normalScaleMult"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--useMetalnessMap"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--metalnessMap"?: ParamValueSerializedTypeMap["node_path"];
  "raymarchedObject-MAT-meshStandard1--metalness"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--useRoughnessMap"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--roughnessMap"?: ParamValueSerializedTypeMap["node_path"];
  "raymarchedObject-MAT-meshStandard1--roughness"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--advanced"?: ParamValueSerializedTypeMap["folder"];
  "raymarchedObject-MAT-meshStandard1--flatShading"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--doubleSided"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--front"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--overrideShadowSide"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--shadowDoubleSided"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--shadowFront"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--colorWrite"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--depthWrite"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--depthTest"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--premultipliedAlpha"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--blending"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-MAT-meshStandard1--dithering"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--polygonOffset"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--polygonOffsetFactor"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-MAT-meshStandard1--polygonOffsetUnits"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-MAT-meshStandard1--wireframe"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-meshStandard1--wireframeLinewidth"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-meshStandard1--wireframeLinecap"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-MAT-meshStandard1--wireframeLinejoin"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-MAT-meshStandard1--useFog"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-rayMarchingBuilder1--default"?: ParamValueSerializedTypeMap["folder"];
  "raymarchedObject-MAT-rayMarchingBuilder1--maxSteps"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-MAT-rayMarchingBuilder1--maxDist"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--surfDist"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--normalsBias"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--textures"?: ParamValueSerializedTypeMap["folder"];
  "raymarchedObject-MAT-rayMarchingBuilder1--useEnvMap"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-rayMarchingBuilder1--envMap"?: ParamValueSerializedTypeMap["node_path"];
  "raymarchedObject-MAT-rayMarchingBuilder1--envMapIntensity"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--envMapRoughness"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--tEnvMapRotate"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-rayMarchingBuilder1--envMapRotation"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--advanced"?: ParamValueSerializedTypeMap["folder"];
  "raymarchedObject-MAT-rayMarchingBuilder1--setBuilderNode"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-rayMarchingBuilder1--builderNode"?: ParamValueSerializedTypeMap["node_path"];
  "raymarchedObject-MAT-rayMarchingBuilder1--doubleSided"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-rayMarchingBuilder1--front"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-rayMarchingBuilder1--overrideCustomMaterials"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-rayMarchingBuilder1--createCustomMatDistance"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-rayMarchingBuilder1--shadowDistanceMin"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--shadowDistanceMax"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--createCustomMatDepth"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-rayMarchingBuilder1--shadowDepthMin"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--shadowDepthMax"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--debug"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-rayMarchingBuilder1--debugMode"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-MAT-rayMarchingBuilder1--debugMinSteps"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-MAT-rayMarchingBuilder1--debugMaxSteps"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-MAT-rayMarchingBuilder1--debugMinDepth"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--debugMaxDepth"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--textureSDF1"?: ParamValueSerializedTypeMap["node_path"];
  "raymarchedObject-MAT-rayMarchingBuilder1--textureSDF1BoundMin"?: ParamValueSerializedTypeMap["vector3"];
  "raymarchedObject-MAT-rayMarchingBuilder1--textureSDF1BoundMin-textureSDF1BoundMinx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--textureSDF1BoundMin-textureSDF1BoundMiny"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--textureSDF1BoundMin-textureSDF1BoundMinz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--textureSDF1BoundMinx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--textureSDF1BoundMiny"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--textureSDF1BoundMinz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--textureSDF1BoundMax"?: ParamValueSerializedTypeMap["vector3"];
  "raymarchedObject-MAT-rayMarchingBuilder1--textureSDF1BoundMax-textureSDF1BoundMaxx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--textureSDF1BoundMax-textureSDF1BoundMaxy"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--textureSDF1BoundMax-textureSDF1BoundMaxz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--textureSDF1BoundMaxx"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--textureSDF1BoundMaxy"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--textureSDF1BoundMaxz"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--offset"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--refractionTint"?: ParamValueSerializedTypeMap["color"];
  "raymarchedObject-MAT-rayMarchingBuilder1--refractionTint-refractionTintr"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--refractionTint-refractionTintg"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--refractionTint-refractionTintb"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--refractionTintr"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--refractionTintg"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-rayMarchingBuilder1--refractionTintb"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-duration1--duration"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-easing1--name"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-MAT-animationsNetwork1-easing1--inOut"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-MAT-animationsNetwork1-target1--type"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-MAT-animationsNetwork1-target1--nodePath"?: ParamValueSerializedTypeMap["node_path"];
  "raymarchedObject-MAT-animationsNetwork1-target1--objectMask"?: ParamValueSerializedTypeMap["string"];
  "raymarchedObject-MAT-animationsNetwork1-target1--updateMatrix"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-animationsNetwork1-target1--printResolve"?: ParamValueSerializedTypeMap["button"];
  "raymarchedObject-MAT-animationsNetwork1-propertyName1--name"?: ParamValueSerializedTypeMap["string"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--mode"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--nodePath"?: ParamValueSerializedTypeMap["node_path"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--objectMask"?: ParamValueSerializedTypeMap["string"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--printResolve"?: ParamValueSerializedTypeMap["button"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--overridePropertyName"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--propertyName"?: ParamValueSerializedTypeMap["string"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--size"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--value1"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--value2"?: ParamValueSerializedTypeMap["vector2"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--value2-value2x"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--value2-value2y"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--value2x"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--value2y"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--value3"?: ParamValueSerializedTypeMap["vector3"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--value3-value3x"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--value3-value3y"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--value3-value3z"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--value3x"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--value3y"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--value3z"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--color"?: ParamValueSerializedTypeMap["color"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--color-colorr"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--color-colorg"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--color-colorb"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--colorr"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--colorg"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--colorb"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--value4"?: ParamValueSerializedTypeMap["vector4"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--value4-value4x"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--value4-value4y"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--value4-value4z"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--value4-value4w"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--value4x"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--value4y"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--value4z"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--value4w"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue1--asColor"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--mode"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--nodePath"?: ParamValueSerializedTypeMap["node_path"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--objectMask"?: ParamValueSerializedTypeMap["string"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--printResolve"?: ParamValueSerializedTypeMap["button"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--overridePropertyName"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--propertyName"?: ParamValueSerializedTypeMap["string"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--size"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--value1"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--value2"?: ParamValueSerializedTypeMap["vector2"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--value2-value2x"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--value2-value2y"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--value2x"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--value2y"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--value3"?: ParamValueSerializedTypeMap["vector3"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--value3-value3x"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--value3-value3y"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--value3-value3z"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--value3x"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--value3y"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--value3z"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--color"?: ParamValueSerializedTypeMap["color"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--color-colorr"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--color-colorg"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--color-colorb"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--colorr"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--colorg"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--colorb"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--value4"?: ParamValueSerializedTypeMap["vector4"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--value4-value4x"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--value4-value4y"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--value4-value4z"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--value4-value4w"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--value4x"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--value4y"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--value4z"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--value4w"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-animationsNetwork1-propertyValue2--asColor"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-animationsNetwork1-PLAY--play"?: ParamValueSerializedTypeMap["button"];
  "raymarchedObject-MAT-animationsNetwork1-PLAY--pause"?: ParamValueSerializedTypeMap["button"];
  "raymarchedObject-MAT-animationsNetwork1-PLAY--stoppable"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-animationsNetwork1-PLAY--debug"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-animationsNetwork1-RESET--play"?: ParamValueSerializedTypeMap["button"];
  "raymarchedObject-MAT-animationsNetwork1-RESET--pause"?: ParamValueSerializedTypeMap["button"];
  "raymarchedObject-MAT-animationsNetwork1-RESET--stoppable"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-animationsNetwork1-RESET--debug"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-animationsNetwork1-CONTROLS--play"?: ParamValueSerializedTypeMap["button"];
  "raymarchedObject-MAT-animationsNetwork1-CONTROLS--pause"?: ParamValueSerializedTypeMap["button"];
  "raymarchedObject-MAT-animationsNetwork1-CONTROLS--reset"?: ParamValueSerializedTypeMap["button"];
  "raymarchedObject-MAT-animationsNetwork1-CONTROLS--stoppable"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-animationsNetwork1-CONTROLS--debug"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-animationsNetwork1-CONTROLS--seek"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-eventsNetwork1-scene1--active"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-eventsNetwork1-scene1--element"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-MAT-eventsNetwork1-scene1--created"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-eventsNetwork1-scene1--ready"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-eventsNetwork1-scene1--play"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-eventsNetwork1-scene1--pause"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-eventsNetwork1-scene1--tick"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-eventsNetwork1-scene1--treachedTime"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-MAT-eventsNetwork1-scene1--reachedTime"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-MAT-eventsNetwork1-scene1--setFrameValue"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-MAT-eventsNetwork1-scene1--setFrame"?: ParamValueSerializedTypeMap["button"];
  "raymarchedObject-MAT-eventsNetwork1-animation1--animation"?: ParamValueSerializedTypeMap["node_path"];
  "raymarchedObject-MAT-eventsNetwork1-animation1--play"?: ParamValueSerializedTypeMap["button"];
  "raymarchedObject-MAT-eventsNetwork1-animation1--pause"?: ParamValueSerializedTypeMap["button"];
  "raymarchedObject-MAT-eventsNetwork1-animation1--stopsPreviousAnim"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-actor1--objectsMask"?: ParamValueSerializedTypeMap["string"];
  "raymarchedObject-actor1--useThisNode"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-actor1--node"?: ParamValueSerializedTypeMap["node_path"];
  "raymarchedObject-actor1-setMaterialUniform1--addPrefix"?: ParamValueSerializedTypeMap["boolean"];
  "raymarchedObject-actor1-setMaterialUniform1--type"?: ParamValueSerializedTypeMap["integer"];
  "raymarchedObject-actor1-setMaterialUniform1--Color"?: ParamValueSerializedTypeMap["color"];
  "raymarchedObject-actor1-setMaterialUniform1--Color-Colorr"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-actor1-setMaterialUniform1--Color-Colorg"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-actor1-setMaterialUniform1--Color-Colorb"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-actor1-setMaterialUniform1--Colorr"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-actor1-setMaterialUniform1--Colorg"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-actor1-setMaterialUniform1--Colorb"?: ParamValueSerializedTypeMap["float"];
  "raymarchedObject-actor1-setMaterialUniform1--uniformName"?: ParamValueSerializedTypeMap["string"];
  "raymarchedObject-actor1-setMaterialUniform1--lerp"?: ParamValueSerializedTypeMap["float"];
}
