<template>
	<PolygonjsScene
		class="h-full w-full"
		:loadFunction="loadFunction"
		:sceneName="'physics_attractor'"
		:displayLoadingProgressBar="false"
		:displayLoadingPoster="true"
		@sceneready="onSceneReady"
		@progress="onProgress"
	/>
</template>

<script lang="ts">
import { defineComponent, computed, ref } from "vue";
// import { PolygonjsScene } from "@polygonjs/vue3";
import PolygonjsScene from "./PolygonjsScene.vue";
import { loadScene_physics_attractor } from "./physics_attractor/autogenerated/loadScene";
import type { PolySceneWithNodeMap_physics_attractor } from "./physics_attractor/autogenerated/PolySceneWithNodeMap";
export default defineComponent({
	name: "physicsAttractor",
	components: {
		PolygonjsScene,
	},
	setup(props) {
		const sceneReady = ref(false);
		let scene: PolySceneWithNodeMap_physics_attractor | undefined;

		function onSceneReady(
			loadedScene: PolySceneWithNodeMap_physics_attractor
		) {
			scene = loadedScene;
			sceneReady.value = true;
		}
		const loadFunction = computed(() => loadScene_physics_attractor);
		function onProgress(progress: number) {}

		return {
			loadFunction,
			sceneReady,
			onSceneReady,
			onProgress,
		};
	},
});
</script>

<style></style>
