<template>
	<div class="absolute top-0 left-0 h-full w-full">
		<div
			:class="[
				'text-xs md:text-base text-gray-400 absolute top-0 right-0 p-0 md:p-2 z-50 transition-opacity text-center md:text-right w-full',
				sceneReady ? 'opacity-100' : 'opacity-0',
			]"
		>
			<span
				class="px-4 py-2 rounded-md bg-teal-800 text-gray-200 cursor-pointer border border-gray-800"
				@click="restart"
				>Restart Game</span
			><span
				class="px-4 py-2 rounded-md bg-violet-800 text-gray-200 cursor-pointer border border-gray-800 ml-1"
				@click="openInEditor"
				>Open In Editor</span
			>
		</div>
		<PolygonjsScene
			class="h-full w-full"
			:loadFunction="loadFunction"
			:sceneName="'player'"
			@sceneready="onSceneReady"
			:displayLoadingProgressBar="false"
			:displayLoadingPoster="true"
		/>
	</div>
</template>

<script lang="ts">
import { defineComponent, computed, ref } from "vue";
// import { PolygonjsScene } from "@polygonjs/vue3";
import PolygonjsScene from "./PolygonjsScene.vue";
import { loadScene_player } from "./player/autogenerated/loadScene";
import type { PolySceneWithNodeMap_player } from "./player/autogenerated/PolySceneWithNodeMap";
export default defineComponent({
	name: "player",
	components: {
		PolygonjsScene,
	},
	setup(props) {
		const sceneReady = ref(false);
		let scene: PolySceneWithNodeMap_player | undefined;

		function onSceneReady(loadedScene: PolySceneWithNodeMap_player) {
			scene = loadedScene;
			sceneReady.value = true;
		}
		const loadFunction = computed(() => loadScene_player);

		function restart() {
			if (!scene) {
				return;
			}
			scene.pause();
			setTimeout(() => scene?.play(), 100);
		}
		function openInEditor() {}

		return {
			loadFunction,
			sceneReady,
			onSceneReady,
			restart,
			openInEditor,
		};
	},
});
</script>

<style></style>
