<template>
	<PolygonjsScene
		class="h-full w-full"
		:loadFunction="loadFunction"
		:sceneName="'player'"
		@sceneready="onSceneReady"
		:displayLoadingProgressBar="false"
		:displayLoadingPoster="true"
	/>
</template>

<script lang="ts">
import { defineComponent, ComputedRef, computed, watch } from "vue";
// import { PolygonjsScene } from "@polygonjs/vue3";
import PolygonjsScene from "./PolygonjsScene.vue";
import { loadScene_player } from "./player/autogenerated/loadScene";
import type { PolySceneWithNodeMap_player } from "./player/autogenerated/PolySceneWithNodeMap";
export default defineComponent({
	name: "player",
	components: {
		PolygonjsScene,
	},
	setup(props) {
		let scene: PolySceneWithNodeMap_player | undefined;

		function onSceneReady(loadedScene: PolySceneWithNodeMap_player) {
			scene = loadedScene;
		}
		const loadFunction = computed(() => loadScene_player);

		return {
			loadFunction,
			onSceneReady,
		};
	},
});
</script>

<style></style>
