<template>
	<PolygonjsScene
		class="h-full w-full"
		:loadFunction="loadFunction"
		:sceneName="'rhino'"
		@sceneready="onSceneReady"
		:displayLoadingProgressBar="false"
		:displayLoadingPoster="false"
	/>
</template>

<script lang="ts">
import { defineComponent, ComputedRef, computed, watch } from "vue";
// import { PolygonjsScene } from "@polygonjs/vue3";
import PolygonjsScene from "./PolygonjsScene.vue";
import { loadScene_rhino } from "./rhino/autogenerated/loadScene";
import type { PolySceneWithNodeMap_rhino } from "./rhino/autogenerated/PolySceneWithNodeMap";
import { Number3 } from "@polygonjs/polygonjs/src/types/GlobalTypes";
import { Vector3Param } from "@polygonjs/polygonjs/src/engine/params/Vector3";
export default defineComponent({
	name: "rhino",
	components: {
		PolygonjsScene,
	},
	props: {
		refractionTint: Object as () => Number3,
		// required: true,
	},
	setup(props) {
		let scene: PolySceneWithNodeMap_rhino | undefined;

		function onSceneReady(loadedScene: PolySceneWithNodeMap_rhino) {
			scene = loadedScene;
		}
		const loadFunction = computed(() => loadScene_rhino);

		const refractionTint: ComputedRef<Number3> = computed(
			() => props.refractionTint || [1, 1, 1]
		);
		watch(refractionTint, _updateSceneColor, { deep: true });

		function _updateSceneColor() {
			if (!scene) {
				return;
			}
			const node = scene.node(
				"/raymarchedObject/actor1/setMaterialUniform1"
			);
			// TODO: remove as unknown
			const param = node.params.get("Color") as unknown as Vector3Param;
			param.set(refractionTint.value);
		}

		return {
			loadFunction,
			onSceneReady,
		};
	},
});
</script>

<style></style>
