<template>
	<div class="relative aspect-w-2 aspect-h-1">
		<div class="h-full">
			<PolygonjsScene
				:loadFunction="loadFunction"
				:sceneName="'scene_01'"
				@sceneready="onSceneReady"
				@viewerready="onViewerReady"
				:displayLoadingProgressBar="false"
				:displayLoadingPoster="false"
			></PolygonjsScene>
		</div>
	</div>
</template>

<script lang="ts">
import {defineComponent, ref, watch, computed} from 'vue';
// import PolygonjsScene from './PolygonjsScene.vue';
import {PolygonjsScene} from '@polygonjs/vue3';
import {loadScene_scene_01} from './scene_01/autogenerated/loadScene';
import type {PolySceneWithNodeMap_scene_01} from './scene_01/autogenerated/PolySceneWithNodeMap';
import type {ThreejsViewer} from '@polygonjs/polygonjs/dist/src/engine/viewers/Threejs';
export default defineComponent({
	name: 'scene-01',
	components: {
		PolygonjsScene,
	},
	setup() {
		let scene: PolySceneWithNodeMap_scene_01 | undefined;

		function onSceneReady(loadedScene: PolySceneWithNodeMap_scene_01) {
			scene = loadedScene;
			// scene.registerOnAfterTick('tick', () => console.log(scene?.frame()));
		}
		function onViewerReady(viewer: ThreejsViewer<any>) {
			// console.log(viewer);
			// viewer.registerOnAfterRender('render', () => console.log('render'));
		}
		const loadFunction = computed(() => loadScene_scene_01);

		return {
			loadFunction,
			onSceneReady,
			onViewerReady,
		};
	},
});
</script>

<style></style>
