<template>
	<section>
		<p>
			<span class="block bg-red-900 relative aspect-w-2 aspect-h-1">
				<span class="h-full">
					<PolygonjsScene
						:loadFunction="loadFunction"
						:sceneName="'scene_01'"
						@sceneready="onSceneReady"
					></PolygonjsScene>
				</span>
			</span>
		</p>
	</section>
</template>

<script lang="ts">
import {defineComponent, ref, watch, computed} from 'vue';
import {PolygonjsScene} from '@polygonjs/vue3';
import {loadScene_scene_01} from './scene_01/autogenerated/loadScene';
import type {PolySceneWithNodeMap_scene_01} from './scene_01/autogenerated/PolySceneWithNodeMap';

export default defineComponent({
	name: 'scene-01',
	components: {
		PolygonjsScene,
	},
	setup() {
		let scene: PolySceneWithNodeMap_scene_01 | undefined;

		function onSceneReady(loadedScene: PolySceneWithNodeMap_scene_01) {
			scene = loadedScene;
		}
		const loadFunction = computed(() => loadScene_scene_01);

		return {
			loadFunction,
			onSceneReady,
		};
	},
});
</script>

<style></style>
