export const EXAMPLE_NAMES = [
	// "By Category/AR/Custom Materials/raymarching",
	// "By Category/AR/basic",
	// "By Category/AR/controllerRay",
	// "By Category/AR/controllerRay2",
	"By Category/Computer Vision/Physics",
	// "By Category/Custom Materials/blink_on_hover_with_instances",
	// "By Category/Custom Materials/blink_on_hover_with_separate_objects",
	// "By Category/Custom Materials/grass",
	"By Category/Custom Materials/raymarchingShadows",
	// "By Category/Custom Materials/texture_distortion",
	// "By Category/Custom Materials/texture_transition",
	"By Category/Custom Materials/transmission_animation",
	"By Category/Effects/Particles/polygonjsLogo",
	// "By Category/Effects/PsychedelicCar",
	"By Category/Effects/TubesFlowingOnCurves",
	// "By Category/Maps/basic",
	// "By Category/Maps/html2D",
	"By Category/Physics/RBDAttractorCursor",
	// "By Category/Physics/basics",
	// "By Category/Using Expressions/bbox",
	// "By Category/Using Expressions/centroid",
	// "By Category/VR/basic",
	"By Category/instancing/stairsAreFun/stairCaseFPS",
	// "By Category/instancing/stairsAreFun/stairCaseMultiple",
	// "By Category/instancing/stairsAreFun/stairCaseSimple",
	// "By Node/actor/AnimationMixer/onScenePlay",
	// "By Node/actor/OnObjectAttributeUpdate/cameraNavigation",
	// "By Node/actor/setObjectLookAt/ClickedObject",
	// "By Node/actor/setObjectLookAt/camera",
	// "By Node/actor/setObjectLookAt/cursor",
	// "By Node/anim/easing",
	// "By Node/anim/target/Animate Nodes",
	// "By Node/anim/target/Animate Scene Graph",
	// "By Node/mat/lineBasic",
	// "By Node/mat/meshBasic",
	"By Node/mat/meshBasicBuilder/CornellBoxLightMaps",
	// "By Node/mat/meshBasicBuilder/blink_multiple",
	// "By Node/mat/meshBasicBuilder/blink_single",
	// "By Node/mat/meshLambert",
	// "By Node/mat/meshMatcap",
	// "By Node/mat/meshNormal",
	// "By Node/mat/meshPhong",
	// "By Node/mat/meshPhysical",
	// "By Node/mat/meshStandard",
	// "By Node/mat/meshToon",
	// "By Node/mat/points",
	"By Node/mat/rayMarchingBuilder/SDFFromObject",
	"By Node/mat/rayMarchingBuilder/multishapes",
	// "By Node/mat/rayMarchingBuilder/primitives",
	// "By Node/mat/rayMarchingBuilder/reflections",
	"By Node/mat/rayMarchingBuilder/refractions",
	"By Node/mat/rayMarchingBuilder/usingAreaLights",
	// "By Node/mat/shadow",
	// "By Node/mat/sky",
	// "By Node/sop/CSS2DObject/basic",
	// "By Node/sop/CSS2DObject/clickable",
	// "By Node/sop/CSS3DObject/basic",
	// "By Node/sop/Decompose/basic",
	// "By Node/sop/add/Create Line",
	// "By Node/sop/add/Create Points",
	// "By Node/sop/attribAddMult",
	// "By Node/sop/attribCopy",
	// "By Node/sop/attribCreate",
	// "By Node/sop/blend",
	// "By Node/sop/box",
	// "By Node/sop/copy/materialsAndTextures",
	// "By Node/sop/copy/withTemplateAttributes",
	// "By Node/sop/data/advanced",
	// "By Node/sop/data/advancedWithCopy",
	// "By Node/sop/data/basic",
	// "By Node/sop/dataUrl",
	// "By Node/sop/file",
	// "By Node/sop/fileGEOJSON",
	// "By Node/sop/instance",
	// "By Node/sop/instance/withTemplateAttributes",
	// "By Node/sop/noise",
	// "By Node/sop/roundedBox",
	// "By Node/sop/sphere/default",
	// "By Node/sop/sphere/icosahedron",
	// "By Node/sop/subdivide",
	// "By Node/sop/switch",
	// "By Node/sop/tetrahedron",
	// "By Node/sop/torus",
	// "By Node/sop/torusKnot",
	// "By Node/sop/uvUnwrap",
];

export const EXAMPLE_LABELS_BY_NAME: Record<string, string> = {
	"By Category/AR/Custom Materials/raymarching": "raymarching",
	"By Category/AR/basic": "basic",
	"By Category/AR/controllerRay": "controllerRay",
	"By Category/AR/controllerRay2": "controllerRay2",
	"By Category/Computer Vision/Physics": "Physics",
	"By Category/Custom Materials/blink_on_hover_with_instances":
		"blink_on_hover_with_instances",
	"By Category/Custom Materials/blink_on_hover_with_separate_objects":
		"blink_on_hover_with_separate_objects",
	"By Category/Custom Materials/grass": "grass",
	"By Category/Custom Materials/raymarchingShadows": "raymarchingShadows",
	"By Category/Custom Materials/texture_distortion": "texture_distortion",
	"By Category/Custom Materials/texture_transition": "texture_transition",
	"By Category/Custom Materials/transmission_animation":
		"transmission_animation",
	"By Category/Effects/Particles/polygonjsLogo": "polygonjsLogo",
	"By Category/Effects/PsychedelicCar": "PsychedelicCar",
	"By Category/Effects/TubesFlowingOnCurves": "TubesFlowingOnCurves",
	"By Category/Maps/basic": "basic",
	"By Category/Maps/html2D": "html2D",
	"By Category/Physics/RBDAttractorCursor": "RBDAttractorCursor",
	"By Category/Physics/basics": "basics",
	"By Category/Using Expressions/bbox": "bbox",
	"By Category/Using Expressions/centroid": "centroid",
	"By Category/VR/basic": "basic",
	"By Category/instancing/stairsAreFun/stairCaseFPS": "stairCaseFPS",
	"By Category/instancing/stairsAreFun/stairCaseMultiple":
		"stairCaseMultiple",
	"By Category/instancing/stairsAreFun/stairCaseSimple": "stairCaseSimple",
	"By Node/actor/AnimationMixer/onScenePlay": "Animate On Play",
	"By Node/actor/OnObjectAttributeUpdate/cameraNavigation":
		"cameraNavigation",
	"By Node/actor/setObjectLookAt/ClickedObject": "ClickedObject",
	"By Node/actor/setObjectLookAt/camera": "Objects Look At Camera",
	"By Node/actor/setObjectLookAt/cursor": "Objects Look At Cursor",
	"By Node/anim/easing": "easing",
	"By Node/anim/target/Animate Nodes": "Animate Nodes",
	"By Node/anim/target/Animate Scene Graph": "Animate Scene Graph",
	"By Node/mat/lineBasic": "lineBasic",
	"By Node/mat/meshBasic": "meshBasic",
	"By Node/mat/meshBasicBuilder/CornellBoxLightMaps": "CornellBoxLightMaps",
	"By Node/mat/meshBasicBuilder/blink_multiple": "blink_multiple",
	"By Node/mat/meshBasicBuilder/blink_single": "blink_single",
	"By Node/mat/meshLambert": "meshLambert",
	"By Node/mat/meshMatcap": "meshMatcap",
	"By Node/mat/meshNormal": "meshNormal",
	"By Node/mat/meshPhong": "meshPhong",
	"By Node/mat/meshPhysical": "meshPhysical",
	"By Node/mat/meshStandard": "meshStandard",
	"By Node/mat/meshToon": "meshToon",
	"By Node/mat/points": "points",
	"By Node/mat/rayMarchingBuilder/SDFFromObject": "SDFFromObject",
	"By Node/mat/rayMarchingBuilder/multishapes": "multishapes",
	"By Node/mat/rayMarchingBuilder/primitives": "primitives",
	"By Node/mat/rayMarchingBuilder/reflections": "reflections",
	"By Node/mat/rayMarchingBuilder/refractions": "refractions",
	"By Node/mat/rayMarchingBuilder/usingAreaLights": "usingAreaLights",
	"By Node/mat/shadow": "shadow",
	"By Node/mat/sky": "sky",
	"By Node/sop/CSS2DObject/basic": "basic",
	"By Node/sop/CSS2DObject/clickable": "clickable",
	"By Node/sop/CSS3DObject/basic": "basic",
	"By Node/sop/Decompose/basic": "Edit Materials After Import",
	"By Node/sop/add/Create Line": "Create Line",
	"By Node/sop/add/Create Points": "Create Points",
	"By Node/sop/attribAddMult": "attribAddMult",
	"By Node/sop/attribCopy": "attribCopy",
	"By Node/sop/attribCreate": "attribCreate",
	"By Node/sop/blend": "blend",
	"By Node/sop/box": "box",
	"By Node/sop/copy/materialsAndTextures": "materialsAndTextures",
	"By Node/sop/copy/withTemplateAttributes": "withTemplateAttributes",
	"By Node/sop/data/advanced": "advanced",
	"By Node/sop/data/advancedWithCopy": "advancedWithCopy",
	"By Node/sop/data/basic": "basic",
	"By Node/sop/dataUrl": "dataUrl",
	"By Node/sop/file": "file",
	"By Node/sop/fileGEOJSON": "GEOJSON",
	"By Node/sop/instance": "Basic",
	"By Node/sop/instance/withTemplateAttributes": "With Template Attributes",
	"By Node/sop/noise": "noise",
	"By Node/sop/roundedBox": "roundedBox",
	"By Node/sop/sphere/default": "default",
	"By Node/sop/sphere/icosahedron": "icosahedron",
	"By Node/sop/subdivide": "subdivide",
	"By Node/sop/switch": "switch",
	"By Node/sop/tetrahedron": "tetrahedron",
	"By Node/sop/torus": "torus",
	"By Node/sop/torusKnot": "torusKnot",
	"By Node/sop/uvUnwrap": "uvUnwrap",
};
